[package]
name = "chat_server"
version = "0.1.0"
authors = ["stargaoyc"]
edition = "2024"
license = "MIT"

[features]
default = []
test-util = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = {workspace = true}
argon2 = { version = "0.5.3", features = ["std"] }
axum = {workspace = true}
axum-extra = {workspace = true}
chrono = {workspace = true}
hex = "0.4.3"
jwt-simple = { workspace = true }
mime_guess = "2.0.5"
serde = {workspace = true}
serde_json = {workspace = true}
serde_yaml = {workspace = true}
sha2 = "0.11.0"
sqlx = {workspace = true}
thiserror = {workspace = true}
tokio = {workspace = true}
tokio-util = { version = "0.7.18", features = ["io"] }
tower = {workspace = true}
tower-http = {workspace = true}
tracing = {workspace = true}
tracing-subscriber = {workspace = true}
chat_core = {workspace = true}

[dev-dependencies]
chat_server = {workspace = true, features = ["test-util"]}
